installkernel: Fix installkernel script
Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>

diff --git a/installkernel b/installkernel
--- a/installkernel
+++ b/installkernel
@@ -68,6 +68,64 @@ validate_modules_install () {
  	fi
 }
 
+install_kernel_from_source () {
+
+LOADER_ENTRY="/boot/loader/entries/linux-${KERNEL_VER}.conf"
+
+if [[ -f /etc/os-release ]]; then
+    . /etc/os-release
+elif [[ -f /usr/lib/os-release ]]; then
+    . /usr/lib/os-release
+fi
+
+if ! [[ $PRETTY_NAME ]]; then
+    PRETTY_NAME="Linux $KERNEL_VERSION"
+fi
+
+declare -a BOOT_OPTIONS
+
+if [[ -f /etc/kernel/cmdline ]]; then
+    read -r -d '' -a BOOT_OPTIONS < /etc/kernel/cmdline
+fi
+
+if ! [[ ${BOOT_OPTIONS[*]} ]]; then
+    read -r -d '' -a line < /proc/cmdline
+    for i in "${line[@]}"; do
+        [[ "${i#initrd=*}" != "$i" ]] && continue
+        BOOT_OPTIONS+=("$i")
+    done
+fi
+
+if ! [[ ${BOOT_OPTIONS[*]} ]]; then
+    echo "Could not determine the kernel command line parameters." >&2
+    echo "Please specify the kernel command line in /etc/kernel/cmdline!" >&2
+    exit 1
+fi
+
+cp "$KERNEL_IMAGE" "${INSTALL_PATH}/vmlinuz-${KERNEL_VER}" &&
+   chown root:root "${INSTALL_PATH}/vmlinuz-${KERNEL_VER}" &&
+   chmod 0644 "${INSTALL_PATH}/vmlinuz-${KERNEL_VER}" || {
+    echo "Could not copy '$KERNEL_IMAGE to '${INSTALL_PATH}/vmlinuz-${KERNEL_VER}'." >&2
+    exit 1
+}
+
+mkdir -p "${LOADER_ENTRY%/*}" || {
+    echo "Could not create loader entry directory '${LOADER_ENTRY%/*}'." >&2
+    exit 1
+}
+
+{
+    echo "title      $PRETTY_NAME"
+    echo "version    $KERNEL_VER"
+    echo "options    ${BOOT_OPTIONS[*]}"
+    echo "linux      /vmlinuz-${KERNEL_VER}"
+} > "$LOADER_ENTRY" || {
+    echo "Could not create loader entry '$LOADER_ENTRY'." >&2
+    exit 1
+}
+exit 0
+}
+
 validate_kernel_version ${KERNEL_VER}
 validate_kernel_image ${KERNEL_IMAGE}
 validate_system_map ${KERNEL_MAP}
@@ -84,8 +142,8 @@ systemctl start boot.mount
 mount -o remount,rw /boot
 ((ret+=$?))
 
-# Use systemd kernel-install script
-kernel-install add $KERNEL_VER $KERNEL_IMAGE
+# Based on systemd kernel-install plugin script
+install_kernel_from_source
 ((ret+=$?))
 
 # Unmount /boot partition
